### PR TITLE
Spectral extraction

### PR DESCRIPTION
**Pull request by joshwalawender**
This PR adds the ability to perform "optimal spectral extraction" as per the method in Horne 1986.

There is an outstanding issue that remains to be solved.  The code runs fine when I run extract_spectra directly, e.g.:

`python ~/git/MosfireDRP/MOSFIRE/Extract.py`

Note: this has hardcoded information in the `if __name__ == '__main__':` section which execute the extraction on TestCase data.  However, if executed as part of Driver.py, e.g.:

`mospy Driver.py`

then it skips my interactive trace fitting, resulting in an error because no traces are defined to extract.  

In addition, this does not yet handle the case where there are multiple stars in a single slit.  Keeping track of that is still a TBD item.

Please take a look and let me know if this looks like a reasonable strategy.  I will continue updating the code this week.

### CODE REVIEW

**Comment by csteidel** [comment]
Josh-
    I am not sure that incorporating spectral extraction is a good idea, as it will
ultimately satisfy only a very small fraction of MOSFIRE users
(many, if not most, MOSIFRE observations do not even involve detected
continuum light at all , since they are faint emission line sources) and
in general require human intervention/decisions when it comes to the extraction. There are
many existing packages (IRAF, IDL, etc.) for extracting and manipulating 1d spectra
after the DRP produces the calibrated 2d spectrograms. That is
actually the original reason that we chose to stop at the 2-D rectified sky subtracted output
and not try to do the next step within the DRP— there are so many different desires
and methods that one would not be able to anticipate — that, and the issue of how best
to do traces when there is no continuum light. In my view, time spent optimizing
the way the 2D background subtraction, stacking,  and (especially) CR rejection (which is currently
sub-optimal) would be much more valuable since they would affect all users.  What you are doing now
will make a few observers happy (probably a very few) happy but will not be particularly useful
to most. Just my $0.02….

     -Chuck Steidel

On Jul 24, 2016, at 2:21 PM, Josh Walawender <notifications@github.com<mailto:notifications@github.com>> wrote:


This PR adds the ability to perform "optimal spectral extraction" as per the method in Horne 1986.

There is an outstanding issue that remains to be solved. The code runs fine when I run extract_spectra directly, e.g.:

python ~/git/MosfireDRP/MOSFIRE/Extract.py

Note: this has hardcoded information in the if __name__ == '__main__': section which execute the extraction on TestCase data. However, if executed as part of Driver.py, e.g.:

mospy Driver.py

then it skips my interactive trace fitting, resulting in an error because no traces are defined to extract.

In addition, this does not yet handle the case where there are multiple stars in a single slit. Keeping track of that is still a TBD item.

Please take a look and let me know if this looks like a reasonable strategy. I will continue updating the code this week.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/Keck-DataReductionPipelines/MosfireDRP/pull/61

Commit Summary

  *   Add optimal spectral extraction routines
  *   Add instructions for interactive fitting. Do some code cleanup, docstrings, etc.
  *   Change to use relative path rather than a hardcoded path.
  *   Handle WCS (under simplifying assumptions). Pass fits.HDUList object out of optimal_extraction.
  *   Expand doc string on TraceFitter. Change TraceFitter behavior to explicitly require a call to fit_traces.
  *   Handle units
  *   Better labeling on plots.
  *   Push outputs (both png and fits files) in to module. Generate better filenames.
  *   Iterate through slits
  *   Add q and n button responses to interactive trace fit. Begin adding support for multiple stars in same slit.
  *   Add extract to AutoDriver
  *   Merge branch 'imcombine' into test_extraction
  *   Fixes
  *   Shorten lines

File Changes

  *   A MOSFIRE/Extract.py<https://github.com/Keck-DataReductionPipelines/MosfireDRP/pull/61/files#diff-0> (578)
  *   M scripts/AutoDriver.py<https://github.com/Keck-DataReductionPipelines/MosfireDRP/pull/61/files#diff-1> (7)

Patch Links:

  *   https://github.com/Keck-DataReductionPipelines/MosfireDRP/pull/61.patch
  *   https://github.com/Keck-DataReductionPipelines/MosfireDRP/pull/61.diff

**Comment by lucarizzi** [comment]
Chuck

We are more or less required to do this. We are bringing the mosfire pipeline into Koa and the other spectral pipelines that are part of the archive have spectral extraction, including the Nirspec one. 

And it has actually been a request we got from a number of observers. If anything, at least to reduce standard stars. 

But by all means your suggestions are great and we should definitely work on that too. We are aiming at a new release in time for the keck science meeting but after that we have time to work on other features. 

Luca

**Comment by joshwalawender** [comment]
Hi Chuck,

Agreed that it would be near impossible to have this handle all cases well.  The intent here is to handle the easy cases for quick look analysis (potentially during observations), not handle all possible cases.  The effort required for this is comparatively low because it does not interact with much other code in the DRP.

FYI, I'm taking a hard look at CR rejection as well, but that goes a bit deeper and interacts with a bit more of the code, so it'll take some time before I have a concrete proposal/plan for that.

aloha,
Josh

**Comment by joshwalawender** [comment]
I've added some updates based on comments from @dmkassis and am now going to merge this in to the 2016release branch, so that the new code is in one place for testing.

**Pull request merged**
